twig:
    file_name_pattern: '*.twig'
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
      remotehost: "%remote_url%"
      locales: "%locales%"
      limits: "%limits%"
      nav: "@App\\Service\\NavigationService"

when@test:
    twig:
        strict_variables: true
