# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locale: 'de'
    remote_url: '%env(string:REMOTE_URL)%'
    remote_ssh: '%env(string:REMOTE_SSH)%'
    limits: [10,50,100,200]
    limit: 100
    model.sortcolumns: [m.purchased,m.name,m.model,m.gtin13,s.name,c.name,sub.name,status.name,manu.name]
    model.sortcolumn: m.purchased
    model.sortorder: desc
    manufacturer.sortcolumns: [name,street,zip,city,logo,vector]
    manufacturer.sortcolumn: name
    manufacturer.sortorder: asc
    dealer.sortcolumns: [name,street,zip,city,logo,vector]
    dealer.sortcolumn: name
    dealer.sortorder: asc
    company.sortcolumns: [name,abbr,logo,vector]
    company.sortcolumn: name
    company.sortorder: asc
    storage.sortcolumns: [name,fill,slot,color]
    storage.sortcolumn: name
    storage.sortorder: asc
    locales:
        de:
            code: de
            name: Deutsch
        en:
            code: en
            name: English

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
